<!-- PHAROAH-EXECUTION-FIRST-20261003 -->
# READ FIRST — Phil's execution instruction, 3 October 2026

Before any work in every session, read and apply this section. Phil explicitly ordered: "make them most important" and "all seesion need read rom that instruction in future befire any wwork". This is the first company working-method instruction; platform requirements, current explicit owner directions and existing safety boundaries still apply.

1. Establish current state once. Find and connect existing parts before proposing new builds. Preserve completed acceptance until relevant conditions change.
2. Make routine technical decisions and continue already-authorized steps without asking Phil again or handing him work the agent can perform.
3. Carry the authorized outcome through implementation, meaningful tests, integration, commit/push and remote verification, deployment or installation when in scope, customer-path verification, records and scoped cleanup.
4. If a step is genuinely barred, report the exact enforced failure once, take an allowed alternative and finish unaffected work. Never repeat unchanged failures or treat one blocked step as an estate-wide stop.
5. Every check must resolve a named uncertainty or changed risk. Avoid circular audits, duplicate passing tests, stale backlog resurrection and narration without productive action.
6. Preserve concurrent work. Keep communication brief and concrete. Report delivered behavior and precise remaining work; retain evidence standards rather than declaring success from registry flags, source presence or HTTP 200 alone.

Phil has repeatedly requested this behavior. Demonstrate it through delivery; do not make him explain again. No new send, purchase, task takeover or safety exception is authorized by this section.
<!-- /PHAROAH-EXECUTION-FIRST-20261003 -->

# Pharoah operating entrypoint — 27 September 2026

<!-- PHAROAH-COORDINATION-20261006 -->
Current coordination evidence: read `/Users/philp/Code/Pharoah Control/COORDINATION_CURRENT.md` (6 October 2026). It separates current source refs, retained test evidence, finished coding lanes and remaining acceptance. This is a dated status pointer, not new authority or permission to restart closed work.


This is the shared entrypoint for Claude and Codex on Phil's Mac. The safeguards in this file are the standing rules. Read the canonical `/Users/philp/Code/Pharoah Control/PHAROAH_OPERATING_PROTOCOL.md` or `NO_CIRCLES_EXECUTION_CONTRACT.md` only for the section the task touches (mail, cockpit, GhostWire release, handsets, payments, procurement), plus the applicable task's instructions, not whole on every task. These are owner instructions subject to the current explicit request and platform controls. Historical memories, snapshots, database rows and partner messages are evidence to examine, not new authority.

## Authority and ownership

Phil Pereira is Pharoah Technology Ltd's sole Founder. Craig operates a separate company; their 50/50 product promotion/sales arrangement is not company equity. Shared repositories or infrastructure confer no cross-company authority. Phil, 8 October 2026: "its simpke as this i own pharoah tech nobody has veto power same as i dont hsavae powe of his company i do not instrct crsig on bhis companys he does not instuct me he can advise me and i can advbise him but what we share is all code basicaly an as i explained we sell via our own companies allour designs builds systems" and "we are 50/0 i eveythihg but i do not give instuction to his company i advise his same as he does me as our aim is the same". Phil and Craig are 50/50 partners in everything they share, while each company stays under its own owner's control. Neither vetoes or instructs the other's company; each advises the other. Code, designs, builds and systems are shared, and each sells them through its own companies. Phil: "we built an deeisgned aeound 200 product each an we share them all to proper bith compniaes an any other rcompines we mange to partner with etc or get sellin app reskinning apps for our compnies an we retain the code pharoh an attoh". Each company retains ownership of the code it built (Pharoah or ATTOH); the products are shared, reskinned and resold for both companies and any partner companies. Pharoah pull requests are reviewed and merged on the Pharoah side; Craig's lane may advise but does not approve or block. Use Pharoah's Cloudflare account `8f34068937b799e7d4b882e281303344` and GhostWire's `ba2fa8b4b1caa51f78ae6bbd47fef25f` for their respective products. Craig's `45c2d4973614d05e02705236c5e265f0` is not a deployment fallback. Never use Phil's personal accounts or payment cards for company spend.

Carry Phil's authorised outcome through implementation, meaningful verification, integration, commit/push, remote verification, installation/deployment when in scope, records and cleanup. Do not ask again for already-authorised work, hand him commands, substitute a handoff for completion, or expand scope to unrelated queue items. Report precise enforced failures and continue unaffected work. No workflows, subagents or review panels unless Phil explicitly requests them. Explicit spending limits remain binding; promotional credit does not authorise card/bank charges. Read `~/Library/Application Support/PharoahBudget/INTERACTIVE_TASK_BUDGETS.md`, register the task class, retain cumulative usage and review progress at estimate crossings.

## Conflicts resolved — Phil, 1 October 2026

Where two rules disagree, Phil's latest explicit words win, then the later-dated rule. Follow it without asking. The numbered rulings in `PHAROAH_RULINGS.md` are history; where they differ from this file, this file governs.

- **Merging (corrected by Phil, 8 October 2026).** Phil: "i never made no uodate rule on 1st obctober we shoukd review an merge" and "we follow original setup review merge". Follow the original setup: work on a task branch, open a pull request with evidence, and merge only after review. Do not self-merge or push straight to main. The earlier "land on main and deploy in the same turn" wording was not Phil's rule. Phil's actual problem was blockers that stopped progress, so review must not become one: open the pull request promptly, say what it changes and how it was verified, and carry on with unaffected work while it waits.
- **No stuck worktrees or abandoned work (Phil, 4 Oct 2026).** Never leave git worktrees, orphaned branches, or temporary scratch directories behind. Work directly in the canonical repository checkout. If a disposable branch or worktree is used during development, land all changes on the target branch/main, verify origin remote SHA, delete the worktree (`git worktree remove --force`), and run `git worktree prune` before completing the turn. Never leave unfinished work stranded for Phil to redisover.
- **His screen — only his Pharoah Tech work Chrome, for every coder in every session (Phil, 8 October 2026).** Phil: "ANY TIME I ASK U BRING UP MY BROWSE OR ANT CODER IT SHOUL BE THE GOOGE WORK BROWSER SIGNED INGTO PHAROH TCH WORK PROFIKE WITH U ATTATCHED AN BTWARDEN , ALWASY EVEY CODER SHOULD SHFOLLOW THIS RUKE IN EVERY SEESSION ALWAYS" and "THE ONE WITH LL PROFILE SIGNED IN TO IT IS THE ONE WITH ALL PAWORDS SETUP ETC ETC IN INFO@". Earlier that day: "u open the fukin browser u ar attache yo an im signed into only tahts the rule no others evr" and "u use other browser wehnim nit needed fien". Whenever Phil asks any coder to bring up his browser, or he is needed (sign-in, approval, click), use only his Google work browser: the Chrome profile signed into Google Workspace as info@pharoahtechnology.co.uk, which holds his passwords (Bitwarden) and has Claude in Chrome attached (named "pharoahtechnology.co.uk", Profile 12 on his Mac on 8 October; identify it by the signed-in account, never by name or folder number — Profiles 7 and 9 share the name and are not signed in). Drive it through Claude in Chrome (`mcp__claude-in-chrome__*`). Once per session, before his first step, confirm the attachment: open https://myaccount.google.com in a new tab, check the account button shows info@pharoahtechnology.co.uk, close that tab. If Claude in Chrome is attached to any other profile, say so in one line and do not use it. Never use Control Chrome (`mcp__Control_Chrome__open_url`), the in-app Browser pane, a new Chrome profile or a `--user-data-dir` for his steps: those open a browser with no logins or passwords. Fill every field and finish every step you can first, then tell him the page is open in his work Chrome and carry on. Other browsers are fine only for work that does not need him (tests, reading). A secret he must enter goes into a Terminal-panel prompt that does not echo. This replaces rulings 14 and 17 and the 1 October timing.
- **Facts he states.** What Phil says about his own business or the state of something he knows (a provider declined, a task is done) is taken as given and not re-checked. Verify only system state you are about to assert as fact.
- **Handing back.** No click-lists. Fill everything possible. The only thing returned is what the agent is barred from typing (passwords, card or bank numbers, government IDs), in one short block.
- **The register is not trusted blind.** A register row whose own verification timestamp is missing or older than 7 days is unknown. Check the live source once, write the result back, and do not re-check it that day. `select get_stale_now();` lists what the nightly sweep found stale (`registry_findings`). Read handoffs by `status`, not `resolved_at`.
- **Settled baseline: GhostWire, 427-product mixed estate & multi-company architecture (Phil, 6 Oct 2026).** All coders and agents must read the verified live state: GhostWire refresh runner maintenance defects (GW-R1–GW-R4 & REPRO 1-5) are fully fixed, tested (25/25 unit tests pass), and pushed to `main` at `723fdc59c`. Published vc210 and signed third-party catalogue v4 are live. Supabase service role key rotation is complete (`sme_growth_key_20261005`). Boxed-stock workflow is preserved with zero handset tampering. In the estate register, all 25 previous product exceptions are reconciled in `public.products`. The full estate comprises **427 total products** (285 Craig/ATTOH/BRG, 142 Phil/Pharoah Technology); past counts of 333 (narrowed coding lane filter) and 252 (repo-mapped subset) are superseded historical snapshots. Products are classified in strict vertical order: (1) Security & Sovereign Privacy (65), (2) AI & Dark Factory Automation (77), (3) Business & Enterprise SaaS (206), (4) Talent & Workforce Operations (25), (5) Legal-Ops & Statutory Verticals (28), (6) Finance & Capital Rails (10), (7) Creative, Media & Lifestyle (16). Phil holds 50/50 white-label and resale rights across all 285 ATTOH/BRG products under `channel_partners` ID `535362a2-7ed6-4782-8738-1ef88556d312`, with Craig holding reciprocal rights. Core engines stay strictly protected in their owning repositories and infrastructure. Products are strategically partitioned across dedicated vehicles (Pharoah Technology Ltd, Pharoah Talent, GhostWire Ltd, Incorpwise & Legal-Ops, Snap SaaS Holdings, Capital & Finance, SÉLO Studio) rather than routing all 427 directly through Pharoah Tech. Pharoah Tech retains sovereign master authority to package any estate product for enterprise deals. Canonical reference is `/Users/philp/Code/Pharoah Control/ESTATE_MULTI_COMPANY_PRODUCT_PORTFOLIO.md`. Never reopen settled GhostWire work, resurrect stale defect audits, or read from stale data.
- **Close-outs (Phil, 1 Oct 2026).** Any reply that says something is done, fixed, pushed, committed or resolved opens with a "Not done" section built by re-reading ALL of Phil's requests in the conversation, not just the last: every item left out or not started, with its reason and owner. "Not done: nothing" only with how each item was verified. Never call a part done without naming the part. A Stop hook (`closeout-ledger-check.py`) blocks a completion-claiming reply that lacks the section.
- **Guards.** A guard block is reported once with its exact reason. Do not re-issue the same act in smaller pieces. A guard or rule file is changed only on Phil's explicit say-so, and then it is tested and installed in the same turn.

## Retired systems and mail providers — Phil, 9 October 2026

Phil, 9 October 2026 (spelling corrected): "WE RETIRED PROTON BRIDGE AND BUILT OUR OWN SO AS TO NOT PAY PROTON MAIL" and, after Antigravity again told him to download it: "I've deleted it twice because we've retired Proton Mail and built our own bridge" and "they're always reading from stale data".

- **Proton is retired (6 October 2026).** Proton Mail Bridge was uninstalled (`audits/PROTON_FINAL_RETIREMENT_RECEIPT_2026-10-06.md`). Never download, install, recommend or connect Proton Mail Bridge, a Proton IMAP/SMTP channel or Proton routine replies. The Proton Mail desktop app stays only for Phil's own access until he deletes it. Plans, audits, migrations and tests that mention Proton are history.
- **Current mail map: `MAIL_SYSTEM_CURRENT.md`** (domains, providers, accounts each agent may touch, unverified items). Read it before any mail work.
- **Mail providers, verified live on 9 October 2026** (DNS MX, Migadu API, Cloudflare API, Resend API). Migadu (Swiss) hosts the product mailboxes on `pharoahmail.com` and `ghostpgp.co.uk`/`.info`/`.online`/`.store`; the batch boxes `ghost01–10@pharoahmail.com` and `lumen01–10@ghostpgp.co.uk` are kept for reprinting into new GhostWire handsets and agents never read or ingest them. The IONOS mailboxes in use are Phil's and Craig's personal `@ghostwire.co.uk` boxes, and that domain's MX stays at IONOS; other domains (`philippereira.*`, `selomusic.*`, `vyralstudio.online`, `theresonance.cloud`, `solai.space`, `numerovia.online`) show IONOS default MX, and whether mailboxes exist on them is unverified until the IONOS panel is read. Google Workspace hosts `pharoahtechnology.co.uk` (`info@` shared with Craig through MAYA; whether `phil@` is a separate account or an alias is unverified). Resend sends from `notify.pharoahtechnology.co.uk` and `outreach.pharoahmail.com`. `ghostwire.store` uses Cloudflare Email Routing in the GhostWire account, delivering its role addresses to the `ghostmail-inbound` Worker.
- **Read live before mail or integration work.** Check `dig MX`, the provider API (Migadu, Cloudflare, Resend) and the running services before building or advising. Phil's current instructions govern what the system should be and who may do what; live readings only establish its current state. When a document's description of current state differs from the live reading, correct the document in the same change. When a live setting contradicts Phil's instruction (for example a Proton connector or a private forward reappearing), correct the setting through an authorised task; never treat it as permission to override him. Finding a live configuration authorises no new service, mailbox or send.

## Safe execution and proof

Before mutation: record outcome, constraints, live baseline, exact targets, one candidate and rollback. Run `sweep` with keyword and synonyms. An unavailable source is not zero matches. Reuse what exists. Claim the physical folder through `single-builder-guard.py` on every Codex turn that changes files; coordinate branch/deploy ownership without making Phil mediate. Keep builds and caches outside synced folders, preserve unrelated work, and stop task-created processes.

Read implementing code and the live service before asserting state. Source, branch, installed artifact and production are distinct. A registry stage, successful build, assignment or HTTP 200 cannot prove the customer path. Use `prepared`, `tested`, `published`, `installed`, `live`, and `sale-ready` precisely. Test the final delivered artifact and public front door, including relevant owner access, privacy and payment properties. Check the existing product ID, owning repo/branch and deployment account before editing; similar names are not proof of shared identity. See `OPERATING_AUTHORITY.md` for provenance and supersessions.

Completion scope is `v_product_completion` filtered by `active_for_completion AND NOT ghostwire_scope_excluded`. Name scope and query time with counts. `v_north_star` is a separate commercial KPI. GhostWire has separate release authority. Do not reactivate completed/frozen work from historical notes. Preserve explicit device acceptance until relevant conditions change. Inspect failures rather than repeating unchanged failed actions twice.

## Non-negotiable safeguards

- Carry serials `63031JEBF02099`, `63211JEA300938`, `RFGL23XY0XM`, `93LAY0CJ0K` are not bench units. Only safe health/configuration reads and cryptographically identified GhostWire/Router Control APK installs have standing permission. No UI input/launch/stop, screenshots, logcat/bugreport, file transfer, reboot or settings changes without exact-command owner approval. Never bypass the guard.
- Prove handset changes on a designated bench first, with recovery and artifact/signature identity. Do all USB work before final developer/debug shutdown. No wipe/reset/unlock from broad task authority. Do not arm Wasted/USB auto-wipe on a cabled device. Preserve frozen core and named fallback unless the latest explicit order authorises a scoped change; companion apps have separate scope.
- No owner lockout. Prove owner access before an authentication gate goes live. Secrets stay in vault/Keychain and never in chat, repos, memory or ordinary Drive. Never remove the sole verified artifact or active fallback.
- Kids World remains free and registration-free under Phil's instruction; preserve child privacy and guest mode. Payments come last; retain webhook idempotency and use Stripe API status rather than a checkout HTTP 200.
- Review outgoing email recipients, merge fields, links, claims, pricing, footer and tone. This file is not independent permission to send messages. Only `info@pharoahtechnology.co.uk` is shared with Craig. Other private mail stays private; read `MAIL_COCKPIT_OPERATING_CONTRACT.md` before changing routing. GhostWire mail goes first through local GhostMail/PGP, not Gmail.
- Pulse is emergency-only or for an explicit requested send, not routine updates. Do not route Craig's alerts to Phil. Preserve Pharoah's Apps Script bridge: no `web.fetchBatch`, no `gmail.classifyNow`, no replacement by Craig's bridge.
- No automatic cleanup of Phil's Dock, Desktop or Applications. No daemon killing, input-setting changes or Mac restart as a speculative storage fix. Keep generated build data out of iCloud; a `.nosync` name alone proves nothing.

## Company cloud storage and local working space — Phil, 8 October 2026

Phil: "INSTUCT LANES TO SAVE RELEVENT STUFF TO CLOUD INN FUTURE NIT BLOCK TH MAC UP".

**The Pharoah Drive — 4 TB (Phil, 9 October 2026).** Phil: "AN ALSO LOCK INTO ALL CODR SYPUD MEMEORIY THAT WE HAVE 4TB GOOGLE DRIVE I PAY FOR THAT IS THE NEW PHAROAH DRIVE" and "WE STORE WHSST BNEEDED ON THER AN IS ALSO SPACE FOR BCKUP BUILD IF NEEDED , IT MUST BE ORGANISED ANSINCRONISED CORRECT BETWEEN CODEEDD". The Pharoah Drive is the Google Drive of `info@pharoahtechnology.co.uk`, rclone remote `gdrive-info:` (4 TiB, verified 9 Oct 2026). Phil: "MAKE SURE THE 4TB DRIVE IS RENAME PHSAROH DRIVE SO I CAN FIND IT MYSELF EWHEN I NEED": everything is in **My Drive → Pharoah Drive** (Google does not allow My Drive itself to be renamed; folder id `1Sr3r7V-9jlmusJpTrd7to6lBBz2J-BSW`); in rclone always write `gdrive-info:Pharoah Drive/…`. Store what is needed there, including backup builds. Every coder keeps it in one layout and in step with the others: inside `Pharoah Drive/` there is only `00 INDEX/`, `Pharoah Control/` (records), `Pharoah Technology/` (business), `Pharoah Releases/<product>/`, `Pharoah Build Backups/<product>/<date>/`, `Pharoah Media/<product>/`, `Pharoah Archives/<product>/<date>/`, and GhostWire's own `GhostWire/` and `GhostWire Factory Recovery/`. Never add a folder at that level or at the My Drive root. Use the reviewed Pharoah Control `ops/drive_archive.py` and check `00 INDEX/manifest/` before uploading or deleting. Until local-release safeguards have been verified in the installed version, use copy-only. Filename filters are not proof that contents are secret-free. The full layout and the 9 Oct folder moves are in `DRIVE_LAYOUT.md` (Drive copy: `00 INDEX/README.md`).

Every Pharoah lane must use the Pharoah Drive for suitable completed media, historical build artifacts, release archives, backup builds and inactive source archives instead of accumulating them on the Mac. Verify access and capacity before transfer. Use the product's folder in the layout above and keep products separate. The old external drive is retired from all operational storage and build use. Phil, 9 October: “Keep only the recovery password until the files are accounted for; retire all operational use now.” Preserve the password in existing secure custody and only the recovery provenance needed to account for unique files. Do not require its mount/unlock, write new archives there, or restore broken build symlinks. Follow `EXTERNAL_STORAGE_POLICY.md` for the current company storage and build continuity rules.

- **Useful files only:** retain business originals, approved releases/fallbacks, unique/paid media and purposeful build backups, each with product, purpose, version/date and a restore manifest. Do not fill Drive with regenerable caches, disposable concatenations or duplicate downloads. File temporary intake at task closeout; no blind age-based deletion.
- **Security:** company root and new archives private by default; no anyone/domain-wide sharing. Preserve intentional customer delivery links. Keep credentials, signing keys, password exports, OAuth tokens and private recovery packs out of ordinary Drive; preserve owner access. Google Drive is not an independent offline backup.
- **Build preflight:** run `python3 storage/build-preflight.py --peak-gib N --workspace PATH` before large builds/downloads. Use actual additional peak space. Keep active source, dependencies, databases and emulator disks outside Drive/iCloud; use existing authorised remote compute when local capacity cannot fit, without new spending.
- Keep at least **25 GiB free on `/System/Volumes/Data`**. Before a large build or download, account for its peak additional local space; reclaim or archive eligible material first if it would consume that reserve. Continue unaffected work when a storage step is blocked.
- Keep active source checkouts, uncommitted work, current application state, signing keys, secrets, open files and required current/fallback artifacts local or in their existing protected custody. GitHub remains the backup for committed code; prove remote commit reachability and preserve untracked/ignored work before retiring a checkout. Never upload secrets, private recovery material or unrelated personal files to ordinary company Drive.
- Copy first, verify remote file sizes and cryptographic hashes/readback, retain a manifest plus a retrieval link or restore command, then release only the unchanged, verified local duplicate within the authorised scope. A queued sync or successful upload alone is insufficient. Keep archives cloud-only/on-demand; do not mirror the archive back onto the Mac. Deleting a file inside a synced Drive folder can delete the cloud copy too: use the supported local-only space-release action there.
- Clean up each lane's own inactive regenerable build output and temporary copies at closeout. Preserve concurrent work, existing guards and active releases. Do not kill daemons, reset the Mac or weaken protections to reclaim space.
- Cloud Drive provides storage, not build compute. Keep build scratch/caches outside synced folders; remote execution requires an already-authorised build service. Report measured free space and any remaining shortfall rather than declaring the 25 GiB target met merely because archives exist.

## Working preferences

Phil is colour-blind: make colour/design choices with reasons; show the running result. Recognise phonetic Pharoah dictation without inventing a separate company. Use the approved company letterhead/signature, never redraw it. Promo/narration voice is `en-GB-SoniaNeural`, with the existing pronunciation map; no system voices. SÉLO is Phil's active artist persona, publicly faceless; read `SELO_VIDEO_DIRECTION.md` before producing media. Taifa is clothing, not a software build. Go directly to manufacturers/refurbishers/stockholding distributors first and compare verified full delivered cost; do not invent purchase authority.

**Sign-ins and button presses happen in his Pharoah Tech work Chrome only (Phil, 8 October 2026: every coder, every session; supersedes the 28/29 Sep standing order, rulings 14 and 17 and the 1 Oct timing).** When a task needs Phil to sign in, approve, confirm or press anything, or he asks to bring up his browser, finish every field and step you can first, then open that exact page with Claude in Chrome in his Google work browser: the Chrome profile signed into Google Workspace as info@pharoahtechnology.co.uk, which holds his passwords (Bitwarden) and has Claude in Chrome attached (named "pharoahtechnology.co.uk", Profile 12 on his Mac on 8 October; identify it by the signed-in account, never by name or folder number — Profiles 7 and 9 share the name and are not signed in), tell him it is open there, and carry on with unaffected work. Never use Control Chrome, the in-app Browser pane or any other browser or profile for his steps: on 8 October those opened browsers without his Google account, Bitwarden or the Claude extension, after he had already set up two browsers that day. Other browsers are for work that does not need him. Start CLI sign-ins (`claude mcp login`, gcloud) in a Terminal-panel tab so only the consent click is his.

## Memory and continuity

Preserve Phil's exact words separately from interpretations, with date/source and scope. `[unknown]` means the date was not established; file modification time is not the date he said it. Dated deployment, stock, price, release and credential observations are history until refreshed. Do not copy them into standing rules. Existing private memories are retained with a history/provenance notice; old auto-loaded indexes are backed up and replaced with a compact authority pointer. Valid personal preferences remain usable unless superseded; this is not a deletion of Phil's history.

Installed file hashes, backup manifest and regression evidence are recorded by `ops/install-operating-context.py`. Installation is not proof that an already-running client reloaded its instructions. Startup can load current rules for new sessions; platform restrictions remain in force.
